### ISSUE TITLE
Issue with name of license

### ISSUE THREAD

**Issue by justinmclean** [ntoll/BFD#1]
Hi,

The ASF doesn't allow a modified Apache license to be referred to as an Apache license [1] Names like "Apache License with such-and-such clause", for example, are not acceptable. We require that you use our trademark "Apache" in a way to prevent user confusion between your license and the Apache License.

Possible ways to fix this include:
  a) Adopt one of the licenses with similar aims such as the SSPL license
  b) Take the text of the Apache license and
           - change the title
           - Update the version and date information
           - Remove / replace the URL
           - add your additional terms and conditions
           - add a sentence just after (or just before) the terms and conditions along these lines: "The license contains all the 
             terms and conditions of the Apache License, version 2 along with the addition of 10 and 11" 

You might be able to think of other ways to also meet this requirement.

Kind Regards,
Justin Mclean

1. https://www.apache.org/foundation/license-faq.html#mod-license

**Comment by ntoll** [comment]
Aha! Thank you @justinmclean for bringing this to my attention. Obviously, the last thing I want to do is "the wrong thing" :tm: and this is an honest mistake on my part. Let me figure out the best course of action in the long run (thank you for your helpful suggestions, I'll obtain some speedy advice) but in the meantime, so as to speedily address your concerns, I'll do a quick search/replace so your suggestion "b" mitigates the problematic current state of affairs until I've a proper solution. Thanks again :+1:

**Comment by justinmclean** [comment]
Thanks for the prompt reply and for respecting the ASF trademark. If you need me to review anything just reach out and I'd be happy to help.

**Comment by ntoll** [comment]
Thank you. I assume you've been in touch with [Heather Meeker](https://heathermeeker.com/about-me/) (creator of the [common clause](https://commonsclause.com/) "modification"). As you'll probably know, she uses the Apache 2.0 license as an example use-case in the docs at the linked-to common clause website.

**Comment by justinmclean** [comment]
I'm not aware if anyone from the ASF has approached her or the maintainers of that site but I don't think so. I'll reach out and see if they would be willing to change it. Thanks for bringing it to my attention.

**Comment by ntoll** [comment]
@justinmclean once again, thanks for the heads up. I've (temporarily) replaced the Apache license with the MIT one, while I work out a longer term solution. :+1:
